name       : python-importlib-metadata
version    : 2.1.1
release    : 10
source     :
    - https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-2.1.1.tar.gz : b8de9eff2b35fb037368f28a7df1df4e6436f578fa74423505b6c6a778d5b5dd
homepage   : https://github.com/python/importlib_metadata
license    : GPL-2.0-or-later
component  : programming.python
summary    : A library to access the metadata for a Python package
description: |
    importlib_metadata is a library to access the metadata for a Python package. This package supplies third-party access to the functionality of importlib.metadata including improvements added to subsequent Python versions.
builddeps  :
    - python-build
    - python-importlib-resources # check
    - python-installer
    - python-fakefs # check
    - python-packaging
    - python-pytest # check
    - python-zipp
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-zipp
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3
