name       : python-importlib-metadata
version    : 0.23
release    : 3
source     :
    - https://files.pythonhosted.org/packages/5d/44/636bcd15697791943e2dedda0dbe098d8530a38d113b202817133e0b06c0/importlib_metadata-0.23.tar.gz : aa18d7378b00b40847790e7c27e11673d7fed219354109d0e7b9e5b25dc3ad26
license    : GPL-2.0-or-later
component  : python.library
summary    : importlib_metadata is a library to access the metadata for a Python package.
description: |
    importlib_metadata is a library to access the metadata for a Python package. It is intended to be ported to Python 3.8.
builddeps  :
    - python-contextlib2
    - python-configparser
    - python-importlib-resources
    - pytest-runner
    - python-zipp
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-contextlib2
    - python-configparser
    - python-importlib-resources
    - python-zipp
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python_setup
    %python3_setup
install    : |
    %python3_install
    %python_install
