name       : python-importlib-metadata
version    : 5.2.0
release    : 13
source     :
    - https://pypi.io/packages/source/i/importlib_metadata/importlib_metadata-5.2.0.tar.gz : 404d48d62bba0b7a77ff9d405efd91501bef2e67ff4ace0bed40a0cf28c3c7cd
homepage   : https://github.com/python/importlib_metadata
license    : GPL-2.0-or-later
component  : programming.python
summary    : A library to access the metadata for a Python package
description: |
    importlib_metadata is a library to access the metadata for a Python package. This package supplies third-party access to the functionality of importlib.metadata including improvements added to subsequent Python versions.
builddeps  :
    - python-build
    #- python-importlib-resources # check
    - python-installer
    #- python-fakefs              # check
    - python-packaging
    #- python-pytest              # check
    - python-zipp
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-zipp
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 -v
